/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetosofted;

import javax.swing.JOptionPane;

/**
 *
 * @author HD
 */
public class SegundoNivel extends javax.swing.JFrame {

    /**
     * Creates new form Fase2
     */
    int i = 1;
    boolean resposta = false;
    int pontos = 0;
    boolean corretude = false;
    int combo = 0;
    public SegundoNivel() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }
    
    public String mostrarPontos(){
        return String.format(""+ pontos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelResposta = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNomeGesto = new javax.swing.JLabel();
        jButtonOi = new javax.swing.JButton();
        jButtonMeuNome = new javax.swing.JButton();
        jButtonNao = new javax.swing.JButton();
        jButtonTudoBem = new javax.swing.JButton();
        jButtonSim = new javax.swing.JButton();
        jButtonTchau = new javax.swing.JButton();
        jLabelMensagem = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jLabelPontos = new javax.swing.JLabel();
        jLabelNomePontos = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Invisivel.png"))); // NOI18N
        getContentPane().add(jLabelResposta);
        jLabelResposta.setBounds(400, 570, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Gestos-Comuns.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 30, 680, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/OI-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(180, 250, 110, 130);

        jLabelNomeGesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/NomeGesto.png"))); // NOI18N
        getContentPane().add(jLabelNomeGesto);
        jLabelNomeGesto.setBounds(70, 310, 100, 50);

        jButtonOi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Oi.png"))); // NOI18N
        jButtonOi.setBorderPainted(false);
        jButtonOi.setContentAreaFilled(false);
        jButtonOi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonOiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonOiMouseExited(evt);
            }
        });
        jButtonOi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOiActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonOi);
        jButtonOi.setBounds(610, 200, 50, 40);

        jButtonMeuNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Meu-nome-e.png"))); // NOI18N
        jButtonMeuNome.setBorderPainted(false);
        jButtonMeuNome.setContentAreaFilled(false);
        jButtonMeuNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMeuNomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMeuNomeMouseExited(evt);
            }
        });
        jButtonMeuNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuNomeActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMeuNome);
        jButtonMeuNome.setBounds(610, 400, 260, 40);

        jButtonNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Nao.png"))); // NOI18N
        jButtonNao.setBorderPainted(false);
        jButtonNao.setContentAreaFilled(false);
        jButtonNao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonNaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonNaoMouseExited(evt);
            }
        });
        jButtonNao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNaoActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonNao);
        jButtonNao.setBounds(610, 300, 90, 40);

        jButtonTudoBem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Tudo-Bem.png"))); // NOI18N
        jButtonTudoBem.setBorderPainted(false);
        jButtonTudoBem.setContentAreaFilled(false);
        jButtonTudoBem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTudoBemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTudoBemMouseExited(evt);
            }
        });
        jButtonTudoBem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTudoBemActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTudoBem);
        jButtonTudoBem.setBounds(610, 450, 210, 40);

        jButtonSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Sim.png"))); // NOI18N
        jButtonSim.setBorderPainted(false);
        jButtonSim.setContentAreaFilled(false);
        jButtonSim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSimMouseExited(evt);
            }
        });
        jButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSim);
        jButtonSim.setBounds(610, 350, 90, 40);

        jButtonTchau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Tchau.png"))); // NOI18N
        jButtonTchau.setBorderPainted(false);
        jButtonTchau.setContentAreaFilled(false);
        jButtonTchau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonTchauMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonTchauMouseExited(evt);
            }
        });
        jButtonTchau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTchauActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTchau);
        jButtonTchau.setBounds(610, 250, 130, 40);

        jLabelMensagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Mensagem.png"))); // NOI18N
        getContentPane().add(jLabelMensagem);
        jLabelMensagem.setBounds(350, 150, 610, 20);

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png"))); // NOI18N
        jButtonContinuar.setBorderPainted(false);
        jButtonContinuar.setContentAreaFilled(false);
        jButtonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseExited(evt);
            }
        });
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(390, 660, 220, 51);

        jLabelPontos.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabelPontos.setForeground(new java.awt.Color(51, 51, 51));
        jLabelPontos.setText("0");
        getContentPane().add(jLabelPontos);
        jLabelPontos.setBounds(100, 130, 140, 50);

        jLabelNomePontos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Pontos-.png"))); // NOI18N
        getContentPane().add(jLabelNomePontos);
        jLabelNomePontos.setBounds(0, 150, 98, 28);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/tilAmarelo.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(620, 290, 73, 23);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/acentoAmarelo.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(820, 390, 60, 30);

        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Voltar.png"))); // NOI18N
        jButtonInicio.setBorderPainted(false);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonInicioMouseExited(evt);
            }
        });
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio);
        jButtonInicio.setBounds(10, 660, 140, 50);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/newBackground.png"))); // NOI18N
        jLabelFundo.setMaximumSize(new java.awt.Dimension(1000, 800));
        jLabelFundo.setMinimumSize(new java.awt.Dimension(1000, 800));
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 1000, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonOiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOiMouseEntered
        jButtonOi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/OiBrilho.png")));
    }//GEN-LAST:event_jButtonOiMouseEntered

    private void jButtonOiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOiMouseExited
        jButtonOi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Oi.png")));
    }//GEN-LAST:event_jButtonOiMouseExited

    private void jButtonTchauMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTchauMouseEntered
        jButtonTchau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/TchauBrilho.png")));
    }//GEN-LAST:event_jButtonTchauMouseEntered

    private void jButtonTchauMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTchauMouseExited
        jButtonTchau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Tchau.png")));
    }//GEN-LAST:event_jButtonTchauMouseExited

    private void jButtonNaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNaoMouseEntered
        jButtonNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/NaoBrilho.png")));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/tilAmareloBrilho.png")));
    }//GEN-LAST:event_jButtonNaoMouseEntered

    private void jButtonNaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonNaoMouseExited
        jButtonNao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Nao.png")));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/tilAmarelo.png")));
    }//GEN-LAST:event_jButtonNaoMouseExited

    private void jButtonSimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimMouseEntered
         jButtonSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/SimBrilho.png")));
    }//GEN-LAST:event_jButtonSimMouseEntered

    private void jButtonSimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSimMouseExited
         jButtonSim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Sim.png")));
    }//GEN-LAST:event_jButtonSimMouseExited

    private void jButtonMeuNomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMeuNomeMouseEntered
         jButtonMeuNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Meu-nome-eBrilho.png")));
         jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/acentoAmareloBrilho.png")));
    }//GEN-LAST:event_jButtonMeuNomeMouseEntered

    private void jButtonMeuNomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMeuNomeMouseExited
         jButtonMeuNome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Meu-nome-e.png")));
         jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/acentoAmarelo.png")));
    }//GEN-LAST:event_jButtonMeuNomeMouseExited

    private void jButtonTudoBemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTudoBemMouseEntered
        jButtonTudoBem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Tudo-BemBrilho.png")));
    }//GEN-LAST:event_jButtonTudoBemMouseEntered

    private void jButtonTudoBemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTudoBemMouseExited
        jButtonTudoBem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Tudo-Bem.png")));
    }//GEN-LAST:event_jButtonTudoBemMouseExited

    private void jButtonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseEntered
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/ContinuarBrilho.png")));
    }//GEN-LAST:event_jButtonContinuarMouseEntered

    private void jButtonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseExited
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png")));
    }//GEN-LAST:event_jButtonContinuarMouseExited

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        if(resposta == false){
            JOptionPane.showMessageDialog(null, "Selecione uma opção");
        }else{
            //ao clicar no botão continuar depois de escolher uma opção
            jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Invisivel.png")));
            i++;
            resposta = false;
            
            switch(i){
               
                case 2:
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/TCHAU-unscreen.gif")));
                    break;
                case 3:
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/TUDOBEM-unscreen.gif")));
                    break;
                case 4:
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/NAO-unscreen.gif")));
                    break;
                case 5:
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/SIM-unscreen.gif")));
                    break;
                case 6:
                    jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/MEU-NOME--unscreen.gif")));
                    break;
            }
        }
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonOiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOiActionPerformed
        switch(i){
            case 1:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Correto.png")));
                resposta = true;
                //pontuação
                pontos += 10;
                combo += 1;
                jLabelPontos.setText(mostrarPontos());
                break;
            case 2:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 3:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 4:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 5:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 6:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
        }
    }//GEN-LAST:event_jButtonOiActionPerformed

    private void jButtonTchauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTchauActionPerformed
        switch(i){
            case 1:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
                combo = 1;
                break;
            case 2:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Correto.png")));
                resposta = true;
                //pontuação
                pontos += 10;
                combo += 1;
                jLabelPontos.setText(mostrarPontos());
                break;
            case 3:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 4:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 5:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 6:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
        }
    }//GEN-LAST:event_jButtonTchauActionPerformed

    private void jButtonNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNaoActionPerformed
        switch(i){
            case 1:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
                combo = 1; 
                break;
            case 2:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 3:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
                combo = 1;
                break;
            case 4:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Correto.png")));
                resposta = true;
                //pontuação
                pontos += 10;
                combo += 1;
                if(combo >= 3)
                    pontos *= 2;
                jLabelPontos.setText(mostrarPontos());
                break;
            case 5:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
                combo = 1;
                break;
            case 6:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
        }
    }//GEN-LAST:event_jButtonNaoActionPerformed

    private void jButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimActionPerformed
        switch(i){
            case 1:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
                combo = 1;
                break;
            case 2:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 3:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 4:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 5:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Correto.png")));
                resposta = true;
                //pontuação
                pontos += 10;
                
                combo += 1;
                if(combo >= 3)
                    pontos *= 2;
                jLabelPontos.setText(mostrarPontos());
                break;
            case 6:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
        }
    }//GEN-LAST:event_jButtonSimActionPerformed

    private void jButtonMeuNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuNomeActionPerformed
        switch(i){
            case 1:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
                combo = 1;
                break;
            case 2:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 3:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 4:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 5:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 6:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Correto.png")));
                resposta = true;
                //pontuação
                pontos += 10;
                combo += 1;
                if(combo >= 3)
                    pontos *= 2;
                if(combo == 6)
                    pontos *=2;
                jLabelPontos.setText(mostrarPontos());
                break;
        }
    }//GEN-LAST:event_jButtonMeuNomeActionPerformed

    private void jButtonTudoBemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTudoBemActionPerformed
        switch(i){
            case 1:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
                combo = 1;
                break;
            case 2:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 3:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Correto.png")));
                resposta = true;
                //pontuação
                pontos += 10;
                combo += 1;
                if(combo == 3)
                    pontos *= 2;
               jLabelPontos.setText(mostrarPontos());
                break;
            case 4:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 5:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
            case 6:
                if(resposta == false)
                    jLabelResposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Errado.png")));
                resposta = true;
               combo = 1;
                break;
        }
    }//GEN-LAST:event_jButtonTudoBemActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        
    }//GEN-LAST:event_jButton1MouseExited

    private void jButtonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInicioMouseEntered
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/VoltarBrilho.png")));
    }//GEN-LAST:event_jButtonInicioMouseEntered

    private void jButtonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInicioMouseExited
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Voltar.png")));
    }//GEN-LAST:event_jButtonInicioMouseExited

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        dispose();
        new TutorialFase2().setVisible(true);
    }//GEN-LAST:event_jButtonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SegundoNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SegundoNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SegundoNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SegundoNivel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SegundoNivel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonMeuNome;
    private javax.swing.JButton jButtonNao;
    private javax.swing.JButton jButtonOi;
    private javax.swing.JButton jButtonSim;
    private javax.swing.JButton jButtonTchau;
    private javax.swing.JButton jButtonTudoBem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelMensagem;
    private javax.swing.JLabel jLabelNomeGesto;
    private javax.swing.JLabel jLabelNomePontos;
    private javax.swing.JLabel jLabelPontos;
    private javax.swing.JLabel jLabelResposta;
    // End of variables declaration//GEN-END:variables
}
