/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetosofted;

/**
 *
 * @author HD
 */
public class TutorialFase1 extends javax.swing.JFrame {

    /**
     * Creates new form TutorialFase1
     */
    public TutorialFase1() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLayout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelZERO = new javax.swing.JLabel();
        jLabelUM = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelTeladeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/LayoutNumeros.png"))); // NOI18N
        getContentPane().add(jLabelLayout);
        jLabelLayout.setBounds(330, 50, 380, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/zero.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 290, 40, 38);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/um.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(260, 290, 40, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/dois.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 290, 40, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/tres.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(620, 290, 40, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/quatro.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(810, 280, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/cinco.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 480, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/seis.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(250, 480, 40, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/sete.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 470, 40, 38);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/oito.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(650, 470, 40, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/nove.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(810, 470, 40, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/acento.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(410, 30, 20, 30);

        jLabelZERO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoZero.png"))); // NOI18N
        getContentPane().add(jLabelZERO);
        jLabelZERO.setBounds(80, 250, 100, 90);

        jLabelUM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoUm.png"))); // NOI18N
        getContentPane().add(jLabelUM);
        jLabelUM.setBounds(290, 250, 80, 110);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoDois.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(490, 250, 80, 90);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoTres.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(660, 230, 90, 140);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoQuatro.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(860, 240, 90, 110);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoCinco.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(120, 440, 80, 100);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoSeis.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(290, 440, 110, 80);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoSete.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(500, 430, 100, 110);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoOito.png"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(680, 410, 100, 123);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/GestoNove.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(860, 430, 100, 90);

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png"))); // NOI18N
        jButtonContinuar.setBorderPainted(false);
        jButtonContinuar.setContentAreaFilled(false);
        jButtonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseExited(evt);
            }
        });
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(380, 640, 210, 60);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/acentoAmarelo.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(690, 150, 40, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/tilAmarelo.png"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(275, 150, 25, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Números/AbaixoEstao.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(150, 160, 630, 40);

        jLabelTeladeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/newBackground.png"))); // NOI18N
        jLabelTeladeFundo.setFocusable(false);
        getContentPane().add(jLabelTeladeFundo);
        jLabelTeladeFundo.setBounds(0, 0, 1070, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseEntered
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/ContinuarBrilho.png")));
    }//GEN-LAST:event_jButtonContinuarMouseEntered

    private void jButtonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseExited
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png")));
    }//GEN-LAST:event_jButtonContinuarMouseExited

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        new PrimeiroNivel1().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialFase1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialFase1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLayout;
    private javax.swing.JLabel jLabelTeladeFundo;
    private javax.swing.JLabel jLabelUM;
    private javax.swing.JLabel jLabelZERO;
    // End of variables declaration//GEN-END:variables
}
