/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetosofted;

/**
 *
 * @author HD
 */
public class TutorialFase3p2 extends javax.swing.JFrame {

    /**
     * Creates new form TutorialFase1
     */
    public TutorialFase3p2() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLayout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelZERO = new javax.swing.JLabel();
        jLabelUM = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelTeladeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/Alfabeto.png"))); // NOI18N
        getContentPane().add(jLabelLayout);
        jLabelLayout.setBounds(330, 30, 690, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/P.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 200, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/S.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 200, 54, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/R.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 200, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/Q.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 200, 60, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/T.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(830, 200, 60, 52);

        jLabelZERO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_P.png"))); // NOI18N
        getContentPane().add(jLabelZERO);
        jLabelZERO.setBounds(70, 170, 110, 90);

        jLabelUM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_S.png"))); // NOI18N
        getContentPane().add(jLabelUM);
        jLabelUM.setBounds(670, 120, 130, 140);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_R.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 130, 90, 140);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_Q.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 130, 100, 140);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_T.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(870, 100, 120, 160);

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png"))); // NOI18N
        jButtonContinuar.setBorderPainted(false);
        jButtonContinuar.setContentAreaFilled(false);
        jButtonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseExited(evt);
            }
        });
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(380, 650, 210, 60);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/U.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 360, 60, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_U.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(70, 290, 90, 130);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/V.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 360, 60, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_V.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(270, 290, 70, 140);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_W.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 290, 100, 140);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/W.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 360, 50, 50);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/X.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(620, 360, 54, 52);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA-X-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(670, 290, 100, 150);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/Y.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(830, 350, 50, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_Y.png"))); // NOI18N
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel22MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel22);
        jLabel22.setBounds(100, 440, 170, 210);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/Z.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(30, 540, 50, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA-Z-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(870, 300, 100, 130);

        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Voltar.png"))); // NOI18N
        jButtonVoltar.setBorderPainted(false);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseExited(evt);
            }
        });
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltar);
        jButtonVoltar.setBounds(20, 660, 150, 50);

        jLabelTeladeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/newBackground.png"))); // NOI18N
        jLabelTeladeFundo.setFocusable(false);
        getContentPane().add(jLabelTeladeFundo);
        jLabelTeladeFundo.setBounds(0, 0, 1070, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseEntered
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/ContinuarBrilho.png")));
    }//GEN-LAST:event_jButtonContinuarMouseEntered

    private void jButtonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseExited
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png")));
    }//GEN-LAST:event_jButtonContinuarMouseExited

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        dispose();
        new TerceiroNivel().setVisible(true);
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jLabel22MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseEntered
        
    }//GEN-LAST:event_jLabel22MouseEntered

    private void jButtonVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseEntered
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/VoltarBrilho.png")));
    }//GEN-LAST:event_jButtonVoltarMouseEntered

    private void jButtonVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseExited
        jButtonVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Voltar.png")));
    }//GEN-LAST:event_jButtonVoltarMouseExited

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        dispose();
        new TutorialFase3().setVisible(true);
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3p2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialFase3p2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLayout;
    private javax.swing.JLabel jLabelTeladeFundo;
    private javax.swing.JLabel jLabelUM;
    private javax.swing.JLabel jLabelZERO;
    // End of variables declaration//GEN-END:variables
}
