/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetosofted;

/**
 *
 * @author HD
 */
public class TutorialFase3 extends javax.swing.JFrame {

    /**
     * Creates new form TutorialFase1
     */
    public TutorialFase3() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLayout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelZERO = new javax.swing.JLabel();
        jLabelUM = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabelTeladeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/Alfabeto.png"))); // NOI18N
        getContentPane().add(jLabelLayout);
        jLabelLayout.setBounds(330, 40, 690, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/A.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 222, 50, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/D.PNG"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(630, 220, 54, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/E.PNG"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(820, 220, 60, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/C.PNG"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 220, 50, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/B.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 220, 60, 50);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/F.PNG"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 390, 60, 52);

        jLabelZERO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_A.png"))); // NOI18N
        getContentPane().add(jLabelZERO);
        jLabelZERO.setBounds(70, 190, 110, 90);

        jLabelUM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_D.png"))); // NOI18N
        getContentPane().add(jLabelUM);
        jLabelUM.setBounds(670, 140, 130, 140);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_E.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(870, 140, 110, 140);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_C.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 150, 90, 140);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_B.png"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(260, 150, 100, 140);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_F.png"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(60, 310, 120, 160);

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png"))); // NOI18N
        jButtonContinuar.setBorderPainted(false);
        jButtonContinuar.setContentAreaFilled(false);
        jButtonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseExited(evt);
            }
        });
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(380, 659, 210, 51);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/G.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 390, 60, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_G.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 330, 90, 120);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/H.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 390, 60, 50);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA-H-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(470, 320, 70, 140);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_I.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(660, 320, 100, 140);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/I.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(630, 390, 50, 50);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/J.png"))); // NOI18N
        getContentPane().add(jLabel16);
        jLabel16.setBounds(810, 380, 60, 60);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA-J-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel18);
        jLabel18.setBounds(860, 330, 100, 130);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/K.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(30, 570, 54, 52);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA-K-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel20);
        jLabel20.setBounds(70, 490, 100, 150);

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/L.png"))); // NOI18N
        getContentPane().add(jLabel21);
        jLabel21.setBounds(240, 570, 50, 50);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_L.PNG"))); // NOI18N
        getContentPane().add(jLabel22);
        jLabel22.setBounds(270, 510, 100, 118);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/M.png"))); // NOI18N
        getContentPane().add(jLabel23);
        jLabel23.setBounds(420, 570, 50, 50);

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_M.PNG"))); // NOI18N
        getContentPane().add(jLabel24);
        jLabel24.setBounds(470, 510, 100, 130);

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_N.png"))); // NOI18N
        getContentPane().add(jLabel25);
        jLabel25.setBounds(670, 510, 90, 120);

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/N.png"))); // NOI18N
        getContentPane().add(jLabel26);
        jLabel26.setBounds(630, 570, 60, 52);

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Alfabeto/O.PNG"))); // NOI18N
        getContentPane().add(jLabel27);
        jLabel27.setBounds(810, 570, 50, 50);

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GifLetrasAlfabeto/LETRA_O.PNG"))); // NOI18N
        getContentPane().add(jLabel28);
        jLabel28.setBounds(870, 530, 90, 80);

        jLabelTeladeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/newBackground.png"))); // NOI18N
        jLabelTeladeFundo.setFocusable(false);
        getContentPane().add(jLabelTeladeFundo);
        jLabelTeladeFundo.setBounds(0, 0, 1070, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseEntered
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/ContinuarBrilho.png")));
    }//GEN-LAST:event_jButtonContinuarMouseEntered

    private void jButtonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseExited
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png")));
    }//GEN-LAST:event_jButtonContinuarMouseExited

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        dispose();
        new TutorialFase3p2().setVisible(true);
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialFase3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialFase3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLayout;
    private javax.swing.JLabel jLabelTeladeFundo;
    private javax.swing.JLabel jLabelUM;
    private javax.swing.JLabel jLabelZERO;
    // End of variables declaration//GEN-END:variables
}
