/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetosofted;

/**
 *
 * @author HD
 */
public class TutorialFase2 extends javax.swing.JFrame {

    /**
     * Creates new form TutorialFase1
     */
    public TutorialFase2() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelLayout = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelZERO = new javax.swing.JLabel();
        jLabelUM = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButtonInicio = new javax.swing.JButton();
        jLabelTeladeFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 800));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabelLayout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Gestos-Comuns.png"))); // NOI18N
        getContentPane().add(jLabelLayout);
        jLabelLayout.setBounds(210, 50, 690, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Oi.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 230, 50, 42);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Meu-nome-e.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 420, 252, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Sim.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 410, 80, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Tchau.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(660, 230, 140, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Tudo-Bem.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(290, 230, 210, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/Nao.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(750, 410, 86, 38);

        jLabelZERO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/OI-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabelZERO);
        jLabelZERO.setBounds(90, 190, 110, 90);

        jLabelUM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/MEU-NOME--unscreen.gif"))); // NOI18N
        getContentPane().add(jLabelUM);
        jLabelUM.setBounds(260, 340, 130, 140);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/SIM-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(570, 330, 110, 140);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/TCHAU-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(780, 160, 90, 140);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/TUDOBEM-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(490, 180, 90, 110);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/NAO-unscreen.gif"))); // NOI18N
        getContentPane().add(jLabel17);
        jLabel17.setBounds(840, 320, 120, 160);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/AExpressaoFacial.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 530, 680, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/EDizMuito.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 570, 750, 34);

        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png"))); // NOI18N
        jButtonContinuar.setBorderPainted(false);
        jButtonContinuar.setContentAreaFilled(false);
        jButtonContinuar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonContinuarMouseExited(evt);
            }
        });
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(380, 640, 210, 60);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GestosComuns/tilAmarelo.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 530, 34, 14);

        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Voltar.png"))); // NOI18N
        jButtonInicio.setBorderPainted(false);
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonInicioMouseExited(evt);
            }
        });
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInicio);
        jButtonInicio.setBounds(20, 650, 140, 50);

        jLabelTeladeFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/newBackground.png"))); // NOI18N
        jLabelTeladeFundo.setFocusable(false);
        getContentPane().add(jLabelTeladeFundo);
        jLabelTeladeFundo.setBounds(0, 0, 1070, 800);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonContinuarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseEntered
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/ContinuarBrilho.png")));
    }//GEN-LAST:event_jButtonContinuarMouseEntered

    private void jButtonContinuarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarMouseExited
        jButtonContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Continuar.png")));
    }//GEN-LAST:event_jButtonContinuarMouseExited

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        dispose();
        new SegundoNivel().setVisible(true);
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInicioMouseEntered
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/VoltarBrilho.png")));
    }//GEN-LAST:event_jButtonInicioMouseEntered

    private void jButtonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInicioMouseExited
        jButtonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projetosofted/imagens/Voltar.png")));
    }//GEN-LAST:event_jButtonInicioMouseExited

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
        dispose();
        new Niveis().setVisible(true);
    }//GEN-LAST:event_jButtonInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TutorialFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TutorialFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TutorialFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TutorialFase2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutorialFase2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelLayout;
    private javax.swing.JLabel jLabelTeladeFundo;
    private javax.swing.JLabel jLabelUM;
    private javax.swing.JLabel jLabelZERO;
    // End of variables declaration//GEN-END:variables
}
